#include <map>
#include <memory>
#include "node_propability_table.h"
#include <vector>
#include <cmath>
#include <random>
#include <stdexcept>
#include <algorithm>
#include <string>
#include <sstream>